service: load-testing-demo

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  environment:
    CHROME_PATH: ./headless-chrome/headless_shell
  vpc:
    securityGroupIds:
      - sg-36243a4e
    subnetIds:
      - subnet-462af10f
      - subnet-c81293af
      - subnet-1b3b2843
custom:
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack

functions:
  screenshot:
    description: Imitate to get screenshots
    memorySize: 1536
    timeout: 30
    handler: handler.screenshot
    events:
      - http:
          path: screenshot
          method: get
  requests:
    description: Imitate to parse network reuqests
    memorySize: 1536
    timeout: 30
    handler: handler.requests
    events:
      - http:
          path: getNetworkRequests
          method: get
  clickaround:
    description: Run headless Chromium
    memorySize: 1536
    timeout: 30
    handler: handler.clickaround
    events:
      - http:
          path: clickaround
          method: get